### ISSUE TITLE
XML Loading

### ISSUE THREAD

**Issue by AlexMeuer** [AlexMeuer/FinalYearProject#6]
All scenes (derivatives of [I_Scene](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Scene.hpp)) need to have the capability of creation with xml.
Other classes (e.g. [Path](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Pathing/Path.hpp), used in [Level](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Level.hpp)) will also have to be creatable from xml to allow this to work smoothly.

Xml creation/loading checklist:
- [x] [Level](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Level.hpp)
  - [x] [Path](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Pathing/Path.hpp)
  - [x] [Pawn](XML-Loading/include/Pawn.hpp)
    - [x] [Minion](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Minion.hpp)
    - [x] [Hero](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Hero.hpp)
- [ ] [Menu](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Menu.hpp)

**Comment by Not0nFire** [comment]
Xml creation/loading checklist:
- [ ] [Level](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Level.hpp)
  - [x] [Path](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Pathing/Path.hpp)
  - [ ] [Pawn](XML-Loading/include/Pawn.hpp)
    - [ ] [Minion](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Minion.hpp)
    - [ ] [Hero](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Hero.hpp)
- [ ] [Menu](https://github.com/Not0nFire/FinalYearProject/blob/XML-Loading/include/Menu.hpp)

**Comment by AlexMeuer** [comment]
Wrote xml ctor for Minion, Hero, Pawn, Actor and Collidable.
Commit: https://github.com/Not0nFire/FinalYearProject/commit/42ee60d00106587cc22873598fbe9a22c1253dc6
