### ISSUE TITLE
Game is silent -> Add sound

### ISSUE THREAD

**Issue by AlexMeuer** [AlexMeuer/FinalYearProject#7]
The game need sound (both sound effects and music).
Each scene needs background music and things like combat hits, deaths and tower shots/impacts all require sound effects.
Scenes should have at least one background track, which is okay if it loops perfectly. Otherwise, several different tracks are preferred.
- [x] The game plays a sound effect
- [x] The game plays background music
- [ ] Scenes can have a playlist of tracks
- [ ] Hits/Impacts pick a suitable sound effect at random
- [ ] Pawns play a sound effect on death.
- [ ] Towers play a sound effect upon firing.
- [ ] Mouseover/Clicks on menu items play a sound effect
- [x] Sound Effects use the ResourceManager<>

**Comment by Not0nFire** [comment]
- [x] The game plays a sound effect
- [x] The game plays background music
- [ ] Scenes can have a playlist of tracks
- [ ] Hits/Impacts pick a suitable sound effect at random
- [ ] Pawns play a sound effect on death.
- [ ] Towers play a sound effect upon firing.
- [ ] Mouseover/Clicks on menu items play a sound effect
- [x] Sound Effects use the ResourceManager<>

**Comment by AlexMeuer** [comment]
Merging for Sprint 3.
To be continued.
